Repository 2i2c-org/infrastructure, pull requests merged in 2021-10, with the labels that each got.

#726 Recovering PR #706: Supporting native JupyterHub OAuthenticator alongside Auth0 for our hubs
  config/hubs/schema.yaml
  deployer/__main__.py
  deployer/hub.py
  docs/howto/configure/auth-management.md
  hub-templates/basehub/values.yaml
  secrets/config/hubs/schema.yaml
Labels: type: enhancement, :label: pangeo, impact: med, :label: authentication, needs: review

#728 [BUGFIX] Create JupyterHub key in generated config
  deployer/hub.py
Labels: type: bug, blocked

#729 Updating code comments in deployer/hub.py
  deployer/hub.py
Labels: :label: documentation, impact: low, needs: review

#734 Update auth docs
  docs/howto/configure/auth-management.md
Labels: :label: documentation, :label: authentication, needs: review

#707 Enabling GitHub Teams Authentication for the Pangeo Staging Hub
  config/hubs/pangeo-hubs.cluster.yaml
  secrets/config/hubs/pangeo-hubs.cluster.yaml
Labels: type: enhancement, :label: pangeo, impact: med, :label: authentication, :label: active deployment

#753 Update docs on migrating NFS home directories
  docs/howto/operate/move-hub.md
Labels: :label: documentation, needs: review

#760 Fix failing CI (#311 folow-up)
  deployer/__main__.py
  deployer/utils.py
Labels: type: bug, :label: CI/CD, needs: review
