Repository 2i2c-org/infrastructure, pull requests merged in 2021-08, with the labels that each got.

#538 Enabling private nodes for GKE clusters
  terraform/gcp/buckets.tf
  terraform/gcp/cluster.tf
  terraform/gcp/network.tf
  terraform/gcp/registry.tf
  terraform/gcp/variables.tf
Labels: :label: pangeo, prio: high, type: enhancement

#489 Deploying Cluster for Pangeo
  .sops.yaml
  secrets/pangeo-hubs.json
  terraform/gcp/projects/pangeo-hubs.tfvars
Labels: :label: pangeo

#574 Add docs on manual setup of NFS server
  docs/howto/operate/index.md
  docs/howto/operate/manual-nfs-setup.md
Labels: :label: documentation

#580 Update SWOT image to latest pangeo image
  config/hubs/2i2c.cluster.yaml
  config/hubs/meom-ige.cluster.yaml
Labels: prio: high, support

#613 Use nfs-server-provisioner subchart in support
  support/Chart.yaml
  support/values.yaml
Labels: blocked, need discussion
