Repository 2i2c-org/infrastructure, pull requests merged in 2021-09, with the labels that each got.

#635 Bump jupyterhub chart and hub image to version 1.1.3
  hub-templates/basehub/Chart.yaml
  hub-templates/basehub/values.yaml
  hub-templates/images/hub/Dockerfile
Labels: proj: JMTE

#597 Add config and deploy Pangeo staging hub
  config/hubs/pangeo-hubs.cluster.yaml
  hub-templates/basehub/templates/incluster-nfs.yaml
  hub-templates/basehub/values.yaml
  secrets/pangeo-hubs.json
Labels: type: hub, :label: pangeo

#636 Auth AWS EKS cluster with encrypted AWS credentials
  .github/workflows/deploy-hubs.yaml
  config/hubs/carbonplan.cluster.yaml
  config/hubs/schema.yaml
  deployer/hub.py
  secrets/carbonplan.json
Labels: proj: JMTE

#670 Allow for node auto-provisioning and enable this for Pangeo cluster
  terraform/gcp/cluster.tf
  terraform/gcp/projects/pangeo-hubs.tfvars
  terraform/gcp/variables.tf
Labels: type: enhancement, :label: pangeo, impact: high, :label: active deployment, needs: review

#674 Update Pangeo hub's profile list
  config/hubs/pangeo-hubs.cluster.yaml
Labels: type: enhancement, :label: environment, :label: pangeo, impact: low, :label: active deployment, :label: feature, needs: review

#682 Tweak CI so kops setup step only runs for AWS hubs
  .github/workflows/deploy-hubs.yaml
Labels: type: bug, :label: CI/CD, needs: review

#685 Reinstate the exit_code check from pytest
  deployer/hub.py
Labels: :label: testing, needs: review

#690 Revert to obscuring output from pytest
  deployer/hub.py
Labels: impact: high, needs: review

#700 Add a template for decommissioning a hub
  .github/ISSUE_TEMPLATE/4_decommission-hub.md
Labels: :label: team-process, needs: review

#705 Automatically run `helm dep up` for hub templates in deployment scripts
  .github/actions/deploy/action.yml
  deployer/hub.py
Labels: :label: automation, needs: review

#706 Support native JupyterHub OAuthenticator in 2i2c-managed hubs
  config/hubs/schema.yaml
  deployer/hub.py
  docs/howto/configure/auth-management.md
  hub-templates/basehub/values.yaml
  secrets/config/hubs/schema.yaml
Labels: type: enhancement, :label: authentication, needs: review
