Repository 2i2c-org/infrastructure, pull requests merged in 2022-01, with the labels that each got.

#904 Add more info about hub migration between clusters
  docs/howto/operate/grafana.md
  docs/howto/operate/move-hub.md
  extra_scripts/rsync-active-users.py
Labels: :label: documentation

#934 🔄 Synced file(s) with 2i2c-org/.github
  .github/ISSUE_TEMPLATE/01_new-issue.yml
Labels: sync

#950 Rename tests dir so that it matches the template
  deployer/tests/test-notebooks/basehub/simple.ipynb
Labels: type: bug, :label: testing
